### ISSUE TITLE
Беспорядок в стилях

### ISSUE THREAD

**Issue by kirillgenets** [Vitaly-Yuralevich/tajem#69]
Необходимо навести порядок в стилях, потому что сейчас все свойства перемешаны. Я могу так что-то упустить (да и читать неудобно так) и ты можешь потом в будущем запутаться. Структура стилей внутри селекторов должна быть, т.е. они должны везде идти в определенном порядке. Разбей мысленно все css-свойства которые есть у селекторов твоих в основном на подгруппы и разделяй их пробелами. И они должны идти в таком порядке: от более важных к менее важным.
Вроде такого: позиционирование, display и сопутствуещее, ширина, высота, отступы, границы, а дальше уже всякие фоны, шрифты и т.п. Перепиши все стили так, чтобы они соответствовали какой-то одной опредленной структуре, пожалуйста)
Пример:
```css
.our-story__button {
    display: block;
    width: 120px;
    margin-top: 35px;
    padding: 8px 16px;
    border: 1px solid #19919c;
    
    font-size: 14px;
    font-weight: 700;
    text-transform: uppercase;
    text-decoration: none;
    text-align: center;
    color: #19919c;
    
    transition: 0.1s;
}
```
